name: Deploy to GitHub Pages with Secrets

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create config.js from GitHub Secret
        run: |
          echo "${{ secrets.CONFIG_JS_CONTENT }}" > config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # የፕሮጀክትህን ሙሉ ፋይል ይጭናል
          branch: gh-pages # ወደዚህ ብራንች አውቶማቲክ ዌብሳይቱን ይሰራል
